[package]
name = "raytrace"
version = "0.1.0"
authors = ["rebecca"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
cgmath = "0.17.0"
rand = "0.7.2"
rayon = "1.2.0"
objekt = "0.1.2"